/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author omkarsalian
 */
public class ViewProfileJPanel extends javax.swing.JPanel {
    private JPanel personProcess;
    private PersonDirectory personDirectory;
    private Person person;

    /**
     * Creates new form ViewProfileJPanel
     */
    public ViewProfileJPanel(JPanel container, PersonDirectory directory, Person person) {
        initComponents();
        this.personProcess = container;
        this.personDirectory = directory;
        this.person = person;
        
       
        refreshTextFields();
        setViewMode();
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLastName = new javax.swing.JTextField();
        WorkAddressJPanel = new javax.swing.JPanel();
        lblStreetaddress = new javax.swing.JLabel();
        txtStreetaddress = new javax.swing.JTextField();
        lblUnitnumber = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblzipcode = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        lblPhonenumber = new javax.swing.JLabel();
        txtUnitnumber = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        lblSocialSecuirtyNumber = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        HomeAddressJPanel = new javax.swing.JPanel();
        lblStreetAddress = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        lblUnitNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblZipcode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtUnitNumber = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblCP = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        WorkAddressJPanel.setBackground(new java.awt.Color(204, 204, 204));
        WorkAddressJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WorkAddress", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 15))); // NOI18N
        WorkAddressJPanel.setForeground(new java.awt.Color(0, 51, 153));

        lblStreetaddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStreetaddress.setForeground(new java.awt.Color(0, 51, 153));
        lblStreetaddress.setText("Street Address");

        lblUnitnumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUnitnumber.setForeground(new java.awt.Color(0, 51, 153));
        lblUnitnumber.setText("Unit Number");

        lblcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblcity.setForeground(new java.awt.Color(0, 51, 153));
        lblcity.setText("City");

        lblzipcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblzipcode.setForeground(new java.awt.Color(0, 51, 153));
        lblzipcode.setText("Zipcode");

        lblstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblstate.setForeground(new java.awt.Color(0, 51, 153));
        lblstate.setText("State");

        lblPhonenumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPhonenumber.setForeground(new java.awt.Color(0, 51, 153));
        lblPhonenumber.setText("Phone Number");

        javax.swing.GroupLayout WorkAddressJPanelLayout = new javax.swing.GroupLayout(WorkAddressJPanel);
        WorkAddressJPanel.setLayout(WorkAddressJPanelLayout);
        WorkAddressJPanelLayout.setHorizontalGroup(
            WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WorkAddressJPanelLayout.createSequentialGroup()
                        .addComponent(lblcity)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(WorkAddressJPanelLayout.createSequentialGroup()
                        .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WorkAddressJPanelLayout.createSequentialGroup()
                                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblStreetaddress)
                                        .addComponent(txtStreetaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(txtcity))
                                    .addComponent(txtzipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(59, 59, 59))
                            .addGroup(WorkAddressJPanelLayout.createSequentialGroup()
                                .addComponent(lblzipcode)
                                .addGap(109, 109, 109)))
                        .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblstate)
                            .addComponent(lblUnitnumber)
                            .addComponent(lblPhonenumber)
                            .addComponent(txtstate, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtUnitnumber)
                            .addComponent(txtphonenumber))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        WorkAddressJPanelLayout.setVerticalGroup(
            WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetaddress)
                    .addComponent(lblUnitnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(lblstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblzipcode)
                    .addComponent(lblPhonenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSocialSecuirtyNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSocialSecuirtyNumber.setForeground(new java.awt.Color(0, 51, 153));
        lblSocialSecuirtyNumber.setText("Social Secuirty Number");

        lblAge.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 51, 153));
        lblAge.setText("Age");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblHeight.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(0, 51, 153));
        lblHeight.setText("Height");

        lblGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 51, 153));
        lblGender.setText("Gender");

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 51, 153));
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 51, 153));
        lblLastName.setText("LastName");

        HomeAddressJPanel.setBackground(new java.awt.Color(204, 204, 204));
        HomeAddressJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Address", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 15))); // NOI18N
        HomeAddressJPanel.setForeground(new java.awt.Color(0, 51, 153));

        lblStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStreetAddress.setForeground(new java.awt.Color(0, 51, 153));
        lblStreetAddress.setText("Street Address");

        lblUnitNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUnitNumber.setForeground(new java.awt.Color(0, 51, 153));
        lblUnitNumber.setText("Unit Number");

        lblCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 51, 153));
        lblCity.setText("City");

        lblZipcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblZipcode.setForeground(new java.awt.Color(0, 51, 153));
        lblZipcode.setText("Zipcode");

        lblState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(0, 51, 153));
        lblState.setText("State");

        lblPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(0, 51, 153));
        lblPhoneNumber.setText("Phone Number");

        javax.swing.GroupLayout HomeAddressJPanelLayout = new javax.swing.GroupLayout(HomeAddressJPanel);
        HomeAddressJPanel.setLayout(HomeAddressJPanelLayout);
        HomeAddressJPanelLayout.setHorizontalGroup(
            HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeAddressJPanelLayout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(HomeAddressJPanelLayout.createSequentialGroup()
                        .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomeAddressJPanelLayout.createSequentialGroup()
                                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblStreetAddress)
                                        .addComponent(txtStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(txtCity))
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGap(59, 59, 59))
                            .addGroup(HomeAddressJPanelLayout.createSequentialGroup()
                                .addComponent(lblZipcode)
                                .addGap(109, 109, 109)))
                        .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblState, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUnitNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnitNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        HomeAddressJPanelLayout.setVerticalGroup(
            HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(lblUnitNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(lblState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(lblPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 51, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblCP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCP.setForeground(new java.awt.Color(0, 51, 153));
        lblCP.setText("View Profile");

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 153));
        btnBack.setText("<--Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 51, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(lblHeight))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(lblSocialSecuirtyNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(lblFirstName))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lblAge))
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lblLastName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)
                        .addGap(276, 276, 276)
                        .addComponent(lblCP, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeAddressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WorkAddressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSecuirtyNumber)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeAddressJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkAddressJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            personProcess.remove(this);
            Component[] panelStack = personProcess.getComponents();
            JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
            ManageProfileJPanel manageAccountJPanel = (ManageProfileJPanel) lastPanel;
            manageAccountJPanel.populateTable();
            CardLayout layout = (CardLayout) personProcess.getLayout();
            layout.previous(personProcess);         // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        setEditMode();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String firstName = txtFirstName.getText();
            String lastName = txtLastName.getText();
            String ssnStr = txtSSN.getText();
            String ageStr = txtAge.getText();
            String heightStr = txtHeight.getText();
            String genderStr = txtGender.getText();
            
            if (firstName.isBlank() || lastName.isBlank() ||  txtStreetAddress.getText().isBlank() ||   
                    txtCity.getText().isBlank() || txtState.getText().isBlank() || txtStreetaddress.getText().isBlank() || 
                    txtcity.getText().isBlank() || txtstate.getText().isBlank()) 
            {
                JOptionPane.showMessageDialog(null, "All fields are mandatory", "Warning", JOptionPane.ERROR_MESSAGE);
                return; 
            }
           
            person.setFirstname(firstName);
            person.setLastname(lastName);
            
    // try catch for ssn
            try {
                long ssn = Long.parseLong(ssnStr);  
                person.setSsn(ssn);
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid SSN. Please enter a valid number.", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
    
    // try catch for age
            try {
                int age = Integer.parseInt(ageStr);
                person.setAge(age);
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Age. Please enter a valid number.", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }

    // try catch for height
            try {
                double height = Double.parseDouble(heightStr);
                person.setHeight(height);
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Height. Please enter a valid number.", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            
            if (!genderStr.isEmpty()) {
                    char gender = genderStr.charAt(0);
                if (gender != 'M' && gender != 'F') {
                    JOptionPane.showMessageDialog(null, "Gender must be 'M' or 'F'.", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                person.setGender(gender);
            } 
            else {
                JOptionPane.showMessageDialog(null, "Gender input is empty.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // try catch for Home Address
            Address homeaddress = new Address();
            homeaddress.setStreetaddress(txtStreetAddress.getText());

            try {
                homeaddress.setUnitNumber(Integer.parseInt(txtUnitNumber.getText()));
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Unit Number for Home Address.", "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
                }
            
            homeaddress.setCity(txtCity.getText());
            homeaddress.setState(txtState.getText());

            try {
                homeaddress.setZipcode(Integer.parseInt(txtZipCode.getText()));
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Zip Code for Home Address.", "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
                }

            try {
                homeaddress.setPhonenumber(Integer.parseInt(txtPhoneNumber.getText()));
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Phone Number for Home Address.", "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
                }

            // Create and set Work Address
            Address workaddress = new Address();
            workaddress.setStreetaddress(txtStreetaddress.getText());

            try {
                workaddress.setUnitNumber(Integer.parseInt(txtUnitnumber.getText()));
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Unit Number for Work Address.", "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
                }

            workaddress.setCity(txtcity.getText());
            workaddress.setState(txtstate.getText());

            try {
                workaddress.setZipcode(Integer.parseInt(txtzipcode.getText()));
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Zip Code for Work Address.", "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
                }

            try {
                workaddress.setPhonenumber(Integer.parseInt(txtphonenumber.getText()));
                } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Phone Number for Work Address.", "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
                }

                person.setHomeAddress(homeaddress);
                person.setWorkAddress(workaddress);

            
            
            JOptionPane.showMessageDialog(this, "Profile saved successfully.", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeAddressJPanel;
    private javax.swing.JPanel WorkAddressJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhonenumber;
    private javax.swing.JLabel lblSocialSecuirtyNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblStreetaddress;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblUnitnumber;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblzipcode;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtStreetaddress;
    private javax.swing.JTextField txtUnitNumber;
    private javax.swing.JTextField txtUnitnumber;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        txtFirstName.setText(person.getFirstname());
        txtLastName.setText(person.getLastname());
        txtSSN.setText(String.valueOf(person.getSsn()));
        txtAge.setText(String.valueOf(person.getAge()));
        txtHeight.setText(String.valueOf(person.getHeight()));
        txtGender.setText(String.valueOf(person.getGender()));
        txtStreetAddress.setText(person.getHomeAddress().getStreetaddress());
        txtUnitNumber.setText(String.valueOf(person.getHomeAddress().getUnitNumber()));
        txtCity.setText(person.getHomeAddress().getCity());
        txtState.setText(person.getHomeAddress().getState());
        txtZipCode.setText(String.valueOf(person.getHomeAddress().getZipcode()));
        txtPhoneNumber.setText(String.valueOf(person.getHomeAddress().getPhonenumber()));
        txtStreetaddress.setText(person.getWorkAddress().getStreetaddress());
        txtUnitnumber.setText(String.valueOf(person.getWorkAddress().getUnitNumber()));
        txtcity.setText(person.getWorkAddress().getCity());
        txtstate.setText(person.getWorkAddress().getState());
        txtzipcode.setText(String.valueOf(person.getWorkAddress().getZipcode()));
        txtphonenumber.setText(String.valueOf(person.getWorkAddress().getPhonenumber()));        

    }
    private void setViewMode(){
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtSSN.setEnabled(false);
        txtAge.setEnabled(false);
        txtHeight.setEnabled(false);
        txtGender.setEnabled(false);
        txtStreetAddress.setEnabled(false);
        txtUnitNumber.setEnabled(false);
        txtCity.setEnabled(false);
        txtState.setEnabled(false);
        txtZipCode.setEnabled(false);
        txtPhoneNumber.setEnabled(false);
        txtStreetaddress.setEnabled(false);
        txtUnitnumber.setEnabled(false);
        txtcity.setEnabled(false);
        txtstate.setEnabled(false);
        txtzipcode.setEnabled(false);
        txtphonenumber.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void setEditMode(){
    
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSSN.setEnabled(true);
        txtAge.setEnabled(true);
        txtHeight.setEnabled(true);
        txtGender.setEnabled(true);
        txtStreetAddress.setEnabled(true);
        txtUnitNumber.setEnabled(true);
        txtCity.setEnabled(true);
        txtState.setEnabled(true);
        txtZipCode.setEnabled(true);
        txtPhoneNumber.setEnabled(true);
        txtStreetaddress.setEnabled(true);
        txtUnitnumber.setEnabled(true);
        txtcity.setEnabled(true);
        txtstate.setEnabled(true);
        txtzipcode.setEnabled(true);
        txtphonenumber.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

}
